"use client"
import type { Metadata } from "next";
import { motion } from "framer-motion";
import "./globals.css";
import { useEffect, useState } from "react";
import Head from "next/head";
import { TbMenu3 } from "react-icons/tb";

export default function RootLayout({
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const [scrolled, setScrolled] = useState(false);
    const [menuOpen, setMenuOpen] = useState(false)

    const handleNavClick = (id: string) => {
        const el = document.getElementById(id);
        if (el) {
            el.scrollIntoView({ behavior: 'smooth' });
            setMenuOpen(false); // Close the menu after clicking the link
        }
    }

    const handleMenuOpen = () => {
        setMenuOpen(!menuOpen)
    }
    useEffect(() => {
        const handleScroll = () => {
        setScrolled(window.scrollY > 50); // Adjust scroll threshold as needed
        };

        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);
    return (
        <html lang="en">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <body
            className={`antialiased`}
        >    <header
      className={`h-fit transition duration-500 z-20 fixed w-full flex justify-between items-center px-3 py-6 ${
        scrolled ? 'bg-secondary shadow-md' : 'bg-background2'
      }`}
    >
      <h3 className="text-2xl font-bold">Hamid</h3>
      <TbMenu3 onClick={handleMenuOpen} size={30} className="text-primary md:hidden" />

      <nav className="hidden md:flex">
        <ul className="flex gap-4 font-medium">
            <li onClick={() => handleNavClick("home")} className="gradien cursor-pointer">Home</li>
            <li onClick={() => handleNavClick("projects")} className="cursor-pointer">Projects</li>
            <li onClick={() => handleNavClick("experience")} className="cursor-pointer">Experience</li>
            <li onClick={() => handleNavClick("skillset")} className="cursor-pointer">Skillset</li>
            <li onClick={() => handleNavClick("contact")} className="cursor-pointer">Contact</li>
        </ul>
      </nav>

      {menuOpen && (
        <motion.div
            initial={{ y: '-100%', opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: '-100%', opacity: 0 }}
            transition={{duration: 0.6}}
        className="w-full h-screen fixed left-0 top-20 bg-secondary z-10 flex flex-col px-4 md:hidden transition-all duration-300">
          <ul className="flex flex-col gap-4 text-lg font-semibold pt-10">
            <li onClick={() => handleNavClick("home")} className="gradien cursor-pointer">Home</li>
            <li onClick={() => handleNavClick("projects")} className="cursor-pointer">Projects</li>
            <li onClick={() => handleNavClick("experience")} className="cursor-pointer">Experience</li>
            <li onClick={() => handleNavClick("skillset")} className="cursor-pointer">Skillset</li>
            <li onClick={() => handleNavClick("contact")} className="cursor-pointer">Contact</li>
          </ul>
        </motion.div>
      )}
    </header>
            
            {children}
        </body>
        </html>
    );
}
