import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body
            className={`antialiased`}
        >
            <header className="z-20 bg-background2 fixed w-full flex justify-between items-center px-3 py-6">
                <h3 className="text-2xl font-bold">Hamid</h3>
                <nav>
                    <ul className="flex gap-2">
                        <li className=" gradien">Home</li>
                        <li>Resume</li>
                        <li>Projects</li>
                    </ul>
                </nav>
            </header>
            
            {children}
        </body>
        </html>
    );
}
