import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <header className="bg-background2 fixed w-full flex justify-between items-center px-3 py-6">
                <h3 className="text-2xl font-bold">Hamid</h3>
                <nav>
                    <ul className="flex gap-2">
                        <li className=" gradien">Home</li>
                        <li>Resume</li>
                        <li>Projects</li>
                    </ul>
                </nav>
            </header>
            
            {children}
        </body>
        </html>
    );
}
